// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

// Generated by scripts/sync-config.py
library Config {
    address public constant ROUTER_MAINNET = 0x92e20164FC457a2aC35f53D06268168e6352b200;
    address public constant ROUTER_SEPOLIA = 0xB587Bc36aaCf65962eCd6Ba59e2DA76f2f575408;
    address public constant TREASURY = 0x598bF63F5449876efafa7b36b77Deb2070621C0E;
    address public constant USDC_MAINNET = 0x833589fCD6eDb6E08f4c7C32D4f71b54bdA02913;
    address public constant USDC_SEPOLIA = 0xeAC1f2C7099CdaFfB91Aa3b8Ffd653Ef16935798;
}
